# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: MyUser
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: brewDb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
